// svkit/src/lib/components/ShopItemsView.svelte
<script lang="ts">
	interface Props {
		orbsInBag: any | null;
		onBuyCommon: (index: number) => Promise<void>;
		onBuyRare: (index: number) => Promise<void>;
		onBuyCosmic: (index: number) => Promise<void>;
		buyingOrbs: Map<string, boolean>;
	}

	let { orbsInBag, onBuyCommon, onBuyRare, onBuyCosmic, buyingOrbs }: Props = $props();

	let currentPage = $state(0);
	const orbsPerPage = 9;

	function getOrbEffect(orb: any | null): { type: string; value: number | string } | null {
		if (!orb || !orb.effect || !orb.effect.option) return null;
		const effect = orb.effect;
		const option = effect.option;
		
		switch (option) {
			case 'Empty':
				return { type: 'Empty', value: '' };
			case 'PointRewind':
				return { type: 'Pt Rewind', value: '' };
			case 'FiveOrDie':
				return { type: '5 or Die', value: '' };
			case 'Point':
				return { type: 'Points', value: effect.Point ?? 0 };
			case 'PointPerOrbRemaining':
				return { type: 'Pts/Orb', value: effect.PointPerOrbRemaining ?? 0 };
			case 'PointPerBombPulled':
				return { type: 'Pts/Bomb', value: effect.PointPerBombPulled ?? 0 };
			case 'GlitchChips':
				return { type: 'Chips', value: effect.GlitchChips ?? 0 };
			case 'Moonrocks':
				return { type: 'Moonrocks', value: effect.Moonrocks ?? 0 };
			case 'Health':
				return { type: 'Health', value: effect.Health ?? 0 };
			case 'Bomb':
				return { type: 'Bomb', value: effect.Bomb ?? 0 };
			case 'Multiplier':
				return { type: 'Multiplier', value: effect.Multiplier ?? 0 };
			case 'BombImmunity':
				return { type: 'Immunity', value: effect.BombImmunity ?? 0 };
			default:
				return null;
		}
	}

	const allOrbs = $derived(() => {
		if (!orbsInBag) return [];
		const common = (orbsInBag.common || []).map((orb: any, idx: number) => ({ ...orb, rarity: 'common', index: idx }));
		const rare = (orbsInBag.rare || []).map((orb: any, idx: number) => ({ ...orb, rarity: 'rare', index: idx }));
		const cosmic = (orbsInBag.cosmic || []).map((orb: any, idx: number) => ({ ...orb, rarity: 'cosmic', index: idx }));
		
		return [...common, ...rare, ...cosmic]
			.filter(orb => getOrbEffect(orb) !== null)
			.sort((a, b) => a.current_price - b.current_price);
	});

	const totalPages = $derived(Math.max(1, Math.ceil(allOrbs().length / orbsPerPage)));

	const currentOrbs = $derived(() => {
		const start = currentPage * orbsPerPage;
		const end = start + orbsPerPage;
		const pageOrbs = allOrbs().slice(start, end);
		const placeholders = Array(orbsPerPage - pageOrbs.length).fill(null);
		return [...pageOrbs, ...placeholders];
	});

	function nextPage() {
		if (currentPage < totalPages - 1) {
			currentPage++;
		}
	}

	function prevPage() {
		if (currentPage > 0) {
			currentPage--;
		}
	}
</script>

<div>
	<div class="flex items-center justify-between mb-4">
		<h2 class="text-xl font-bold">Shop Items</h2>
		{#if totalPages > 1}
			<div class="flex items-center gap-2">
				<button
					onclick={prevPage}
					disabled={currentPage === 0}
					class="px-3 py-1 bg-gray-700 hover:bg-gray-600 disabled:bg-gray-800 disabled:opacity-50 disabled:cursor-not-allowed rounded text-lg"
				>
					&lt;
				</button>
				<span class="text-sm opacity-60">{currentPage + 1}</span>
				<button
					onclick={nextPage}
					disabled={currentPage === totalPages - 1}
					class="px-3 py-1 bg-gray-700 hover:bg-gray-600 disabled:bg-gray-800 disabled:opacity-50 disabled:cursor-not-allowed rounded text-lg"
				>
					&gt;
				</button>
			</div>
		{/if}
	</div>
	<div class="bg-black/30 border border-white/10 p-3 rounded-lg">
		<div class="grid grid-cols-3 gap-3">
			{#each currentOrbs() as orb}
				{@const effect = getOrbEffect(orb)}
				{@const buyKey = `${orb.rarity}-${orb.index}`}
				{@const isBuying = buyingOrbs.get(buyKey) || false}
				{@const borderColor = orb.rarity === 'common' ? 'border-white/50' : orb.rarity === 'rare' ? 'border-blue-500/70' : 'border-purple-500/70'}
				{#if effect}
					<button
						onclick={() => {
							if (orb.rarity === 'common') onBuyCommon(orb.index);
							else if (orb.rarity === 'rare') onBuyRare(orb.index);
							else if (orb.rarity === 'cosmic') onBuyCosmic(orb.index);
						}}
						disabled={isBuying}
						class="aspect-square w-[120px] bg-black/50 hover:bg-black/70 disabled:bg-gray-600 disabled:cursor-not-allowed cursor-pointer p-3 rounded border-2 {borderColor} flex flex-col transition-colors"
					>
						{#if isBuying}
							<div class="text-xs opacity-80 text-center flex-1 flex items-center justify-center">Buying...</div>
						{:else}
						<div class="flex-1 flex flex-col justify-center items-center">
							<div class="text-sm font-bold text-center mb-1">{effect.type}</div>
							<div class="text-sm opacity-80 text-center">
								{effect.value || ''}
							</div>
						</div>
						<div class="grid grid-cols-2 gap-2 w-full text-xs opacity-60">
							<div class="text-left">{orb.current_price} GC</div>
							<div class="text-right">{orb.count}x</div>
						</div>
						{/if}
					</button>
				{:else}
					<div class="aspect-square w-[120px] bg-black/20 p-3 rounded border border-white/5 flex items-center justify-center">
						<div class="opacity-30 text-sm">Empty</div>
					</div>
				{/if}
			{/each}
		</div>
	</div>
</div>

// react_client/src/components/ShopItemsView.tsx
import { useMemo, useState } from 'react'
import type { Orb } from '@/bindings/typescript/models.gen'

interface ShopItemsViewProps {
  orbsInBag: {
    common: Array<Orb>
    rare: Array<Orb>
    cosmic: Array<Orb>
  } | null
  onBuyCommon: (index: number) => Promise<void>
  onBuyRare: (index: number) => Promise<void>
  onBuyCosmic: (index: number) => Promise<void>
  buyingOrbs: Map<string, boolean>
}

function getOrbEffect(orb: Orb | null): { type: string; value: number | string } | null {
  if (!orb || !orb.effect) return null
  
  const effect = orb.effect as any
  
  // Handle CairoCustomEnum structure
  let effectName: string | null = null
  let value: number = 0
  
  if (typeof effect === 'string') {
    effectName = effect
  } else if (typeof effect === 'object') {
    // Check if it has a variant property (e.g., { variant: { Point: 8 } })
    if ('variant' in effect && effect.variant && typeof effect.variant === 'object') {
      const variant = effect.variant as Record<string, any>
      const keys = Object.keys(variant)
      if (keys.length > 0) {
        effectName = keys[0]
        const variantValue = variant[effectName]
        if (variantValue !== undefined && variantValue !== null) {
          value = Number(variantValue)
          if (isNaN(value)) value = 0
        }
      }
    } else {
      // Check if it's a direct enum (e.g., { PointRewind: undefined })
      const keys = Object.keys(effect).filter(key => key !== 'variant')
      if (keys.length > 0) {
        effectName = keys[0]
        const enumValue = effect[effectName]
        if (enumValue !== undefined && enumValue !== null) {
          value = Number(enumValue)
          if (isNaN(value)) value = 0
        }
      }
    }
  }
  
  if (!effectName || effectName === 'Empty') return null
  
  switch (effectName) {
    case 'PointRewind':
      return { type: 'Pt Rewind', value: '' }
    case 'Point':
      return { type: 'Points', value }
    case 'PointPerOrbRemaining':
      return { type: 'Pts/Orb', value }
    case 'PointPerBombPulled':
      return { type: 'Pts/Bomb', value }
    case 'GlitchChips':
      return { type: 'Chips', value }
    case 'Moonrocks':
      return { type: 'Moonrocks', value }
    case 'Health':
      return { type: 'Health', value }
    case 'Bomb':
      return { type: 'Bomb', value }
    case 'Multiplier':
      return { type: 'Multiplier', value }
    case 'BombImmunity':
      return { type: 'Immunity', value }
    default:
      return null
  }
}

export default function ShopItemsView({
  orbsInBag,
  onBuyCommon,
  onBuyRare,
  onBuyCosmic,
  buyingOrbs,
}: ShopItemsViewProps) {
  const [currentPage, setCurrentPage] = useState(0)
  const orbsPerPage = 9

  const allOrbs = useMemo(() => {
    if (!orbsInBag) return []
    const common = (orbsInBag.common || []).map((orb, idx) => ({ ...orb, rarity: 'common' as const, index: idx }))
    const rare = (orbsInBag.rare || []).map((orb, idx) => ({ ...orb, rarity: 'rare' as const, index: idx }))
    const cosmic = (orbsInBag.cosmic || []).map((orb, idx) => ({ ...orb, rarity: 'cosmic' as const, index: idx }))
    
    return [...common, ...rare, ...cosmic]
      .filter(orb => getOrbEffect(orb) !== null)
      .sort((a, b) => Number(a.current_price) - Number(b.current_price))
  }, [orbsInBag])

  const totalPages = Math.max(1, Math.ceil(allOrbs.length / orbsPerPage))

  const currentOrbs = useMemo(() => {
    const start = currentPage * orbsPerPage
    const end = start + orbsPerPage
    const pageOrbs = allOrbs.slice(start, end)
    const placeholders = Array(orbsPerPage - pageOrbs.length).fill(null)
    return [...pageOrbs, ...placeholders]
  }, [allOrbs, currentPage, orbsPerPage])

  const nextPage = () => {
    if (currentPage < totalPages - 1) {
      setCurrentPage(currentPage + 1)
    }
  }

  const prevPage = () => {
    if (currentPage > 0) {
      setCurrentPage(currentPage - 1)
    }
  }

  return (
    <div className="w-full">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-xl font-semibold" style={{ color: '#55DD63' }}>
          Shop Items
        </h2>
        {totalPages > 1 && (
          <div className="flex items-center gap-2">
            <button
              onClick={prevPage}
              disabled={currentPage === 0}
              className="px-3 py-1 rounded-lg text-lg font-semibold transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              style={{
                backgroundColor: currentPage === 0 ? '#14240C' : '#55DD63',
                color: currentPage === 0 ? '#55DD63' : '#0C1806',
                border: currentPage === 0 ? '2px solid #55DD63' : 'none',
              }}
            >
              &lt;
            </button>
            <span className="text-sm opacity-80" style={{ color: '#55DD63' }}>
              {currentPage + 1} / {totalPages}
            </span>
            <button
              onClick={nextPage}
              disabled={currentPage === totalPages - 1}
              className="px-3 py-1 rounded-lg text-lg font-semibold transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              style={{
                backgroundColor: currentPage === totalPages - 1 ? '#14240C' : '#55DD63',
                color: currentPage === totalPages - 1 ? '#55DD63' : '#0C1806',
                border: currentPage === totalPages - 1 ? '2px solid #55DD63' : 'none',
              }}
            >
              &gt;
            </button>
          </div>
        )}
      </div>
      <div className="bg-black/30 border border-white/10 p-4 rounded-lg">
        <div className="grid grid-cols-3 gap-4 justify-items-center">
          {currentOrbs.map((orb, idx) => {
            if (!orb) {
              return (
                <div
                  key={`empty-${idx}`}
                  className="aspect-square w-[120px] bg-black/20 p-3 rounded-lg border border-white/5 flex items-center justify-center"
                >
                  <div className="opacity-30 text-sm" style={{ color: '#55DD63' }}>
                    Empty
                  </div>
                </div>
              )
            }

            const effect = getOrbEffect(orb)
            const buyKey = `${orb.rarity}-${orb.index}`
            const isBuying = buyingOrbs.get(buyKey) || false
            const borderColor =
              orb.rarity === 'common'
                ? '#55DD63'
                : orb.rarity === 'rare'
                  ? '#3B82F6'
                  : '#A855F7'

            if (!effect) return null

            return (
              <button
                key={`${orb.rarity}-${orb.index}`}
                onClick={() => {
                  if (orb.rarity === 'common') onBuyCommon(orb.index)
                  else if (orb.rarity === 'rare') onBuyRare(orb.index)
                  else if (orb.rarity === 'cosmic') onBuyCosmic(orb.index)
                }}
                disabled={isBuying}
                className="aspect-square w-[120px] bg-black/50 hover:bg-black/70 disabled:bg-gray-600 disabled:cursor-not-allowed cursor-pointer p-3 rounded-lg border-2 flex flex-col transition-colors"
                style={{
                  borderColor: isBuying ? '#666' : borderColor,
                }}
              >
                {isBuying ? (
                  <div className="text-xs opacity-80 text-center flex-1 flex items-center justify-center" style={{ color: '#55DD63' }}>
                    Buying...
                  </div>
                ) : (
                  <>
                    <div className="flex-1 flex flex-col justify-center items-center">
                      <div className="text-sm font-bold text-center mb-1" style={{ color: '#55DD63' }}>
                        {effect.type}
                      </div>
                      <div className="text-sm opacity-80 text-center" style={{ color: '#55DD63' }}>
                        {effect.value || ''}
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-2 w-full text-xs opacity-70" style={{ color: '#55DD63' }}>
                      <div className="text-left">{Number(orb.current_price)} GC</div>
                      <div className="text-right">{Number(orb.count)}x</div>
                    </div>
                  </>
                )}
              </button>
            )
          })}
        </div>
      </div>
    </div>
  )
}
