// svk_recs_client/src/routes/+page.svelte
<div class="flex items-center justify-center min-h-screen">
	<div class="text-center">
		<h1 class="text-6xl font-bold mb-8">GLITCHBOMB</h1>
		<div class="grid grid-cols-2 gap-4">
			<a href="/players" class="border border-white p-6 hover:bg-white hover:text-black transition-colors">
				PLAYERS
			</a>
			<a href="/gamepacks" class="border border-white p-6 hover:bg-white hover:text-black transition-colors">
				GAMEPACKS
			</a>
			<a href="/games" class="border border-white p-6 hover:bg-white hover:text-black transition-colors">
				GAMES
			</a>
			<a href="/orbs" class="border border-white p-6 hover:bg-white hover:text-black transition-colors">
				ORBS
			</a>
		</div>
	</div>
</div>

// react_client/src/routes/index.tsx
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/')({
  component: TitleScreen,
})

function TitleScreen() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-black text-white">
      <h1 className="text-6xl font-bold tracking-wider">GLITCHBOMB</h1>
    </div>
  )
}
